sudo: required

services:
  - docker

language: php

php:
  - '7.0'

install:
  - composer config -g github-oauth.github.com $GITHUB_OAUTH_TOKEN
  - composer install

before_script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $DOCKER_REGISTRY

script:
  - docker-compose -f ci/docker-compose.yml run unit
